"""Phase 06 LLM-judge arbitration -- closes Phase 06 one way or the other.

Run: C:\\conda-envs\\drlca-rag\\python.exe scripts\\judge_phase06.py [--limit N] [--dry-run]
     (from D:\\NGORAG)

WHAT THIS SETTLES
-----------------
scripts/eval_phase06.py is a custom ZERO-LLM proxy for the RAGAS metrics. It is
deterministic and free, but its own docstring admits two blind spots: it cannot
see subtle misattribution, and its relevancy metric is a word-overlap FLOOR,
not aboutness. Phase 06 therefore ended with three items nobody had arbitrated:

  A. reverse_rel = 0.630, below the 0.80 gate. Is that a real relevancy
     failure, or an artifact of using reverse retrieval as a proxy?
  B. Q3 and Q8 answers look THIN. Thin-but-correct, or actually incomplete?
  C. The s.39 and s.34 citation dispositions -- the misattributions that used
     to need hand-written MANUAL_FLAGS entries.

An honest FAIL closes Phase 06 just as well as a PASS. The point is a verdict
with reasoning attached, not a better-looking number.

METHODOLOGY: GENERATOR != JUDGE
-------------------------------
Answers under review were generated by `gemini-2.5-flash` (rag.MODEL_NAME).
This script judges with `gemini-2.5-flash-lite` (resolved via
client.models.list() on 2026-09-11 -- a listing call, no generation quota).

Using a different model is a METHODOLOGICAL IMPROVEMENT, not merely a quota
dodge. A model grading its own output shares its own blind spots and tends to
ratify them; the split removes that specific failure mode. It does not remove
judge bias in general -- a Gemini model judging a Gemini model is still not
independent, and that limitation is recorded rather than papered over.

The judge is shown the question, the retrieved context and the answer. It is
NEVER shown the proxy's score for that item, so it cannot anchor on it. The
comparison proxy-vs-judge is done afterwards, in code.

QUOTA DISCIPLINE
----------------
Free tier is ~20 calls/day/model, and the two models have SEPARATE pools, so
this run cannot starve the generator. Tasks are priority-ordered: the 13 that
actually decide A/B/C run first, the 9 supplementary faithfulness checks last.

Every completed call is checkpointed to disk IMMEDIATELY, so a 429 halfway
through loses nothing and a re-run resumes where it stopped. A failed call
records `llm_error` and stays PENDING -- it is never backfilled with a guess.
That is the same rule the Phase 02 harness follows: never fake a row.
"""

import json
import os
import re
import sys
import time
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from bench_phase01 import load_questions  # noqa: E402 (SAME frozen 10Q set)
from eval_phase06 import EXPECTED, ref_nums  # noqa: E402
from rag import MODEL_NAME, build_corpus  # noqa: E402
from retrieve import PerDocRetriever, cite_tag  # noqa: E402

# Resolved by client.models.list() in M0: models/gemini-2.5-flash-lite exists.
JUDGE_MODEL = "gemini-2.5-flash-lite"

TRANSCRIPT = (ROOT / "scripts"
              / "test_phase02_results_cite-strict-v2-fixA2_2026-09-10.json")
CHECKPOINT = ROOT / "scripts" / ".judge_phase06_checkpoint.json"
OUT = ROOT / "scripts" / ("judge_phase06_results_%s_%s.json"
                          % (JUDGE_MODEL, date.today().isoformat()))

K_PER_DOC, TOP_N = 3, 6


# --------------------------------------------------------------------------
# Prompts. Each asks for ONE judgement and a reason, as strict JSON. None of
# them mentions the proxy's score -- the judge must not be anchored.
# --------------------------------------------------------------------------

RELEVANCY_PROMPT = """You are auditing a legal question-answering system for \
Nigerian disability rights. Judge ONE thing only: does the ANSWER actually \
address the QUESTION that was asked?

Judge aboutness, not style, not completeness, not citation correctness. An \
answer that is correct and on-topic but terse is still RELEVANT. An answer \
that discusses a different legal provision than the one asked about is NOT.

QUESTION:
%s

ANSWER:
%s

Reply with ONLY a JSON object, no markdown fence:
{"relevant": true|false, "score": <0.0-1.0>, "reason": "<one sentence>"}"""

THINNESS_PROMPT = """You are auditing a legal question-answering system for \
Nigerian disability rights. The system must answer STRICTLY from retrieved \
excerpts and cite every claim.

Judge ONE thing: given the CONTEXT that was actually available, is the ANSWER \
adequately complete, or did it leave material information on the table?

This is the distinction that matters: an answer is "thin but correct" if the \
context simply did not contain more; it is "incomplete" if the context DID \
contain relevant material the answer ignored. Do not penalise the answer for \
information absent from the context.

QUESTION:
%s

CONTEXT (the only material the system was allowed to use):
%s

ANSWER:
%s

Reply with ONLY a JSON object, no markdown fence:
{"verdict": "adequate"|"thin_but_correct"|"incomplete", \
"missed": "<what was left out, or 'nothing'>", "reason": "<one sentence>"}"""

CITATION_PROMPT = """You are auditing citations in a Nigerian disability-rights \
legal assistant.

CRITICAL: this system uses THREE SEPARATE numbering schemes that must never be \
conflated. "Act clause N" (Discrimination Against Persons with Disabilities \
(Prohibition) Act 2018), "Constitution section N" (1999 Constitution), and \
"Factsheet Section N" are DIFFERENT things. A claim tagged [Constitution s. N] \
must be supported by section N OF THE CONSTITUTION specifically.

CLAIM MADE BY THE SYSTEM:
%s

CITATION TAG ATTACHED TO THAT CLAIM:
%s

TEXT ACTUALLY CARRYING THAT REFERENCE IN THE RETRIEVED CONTEXT:
%s

Judge ONE thing: does the cited reference genuinely support that claim?
- "supported"     : the cited provision says what the claim says.
- "misattributed" : the content is real but belongs to a DIFFERENT provision \
than the one cited.
- "unsupported"   : nothing in the cited text supports the claim.

Reply with ONLY a JSON object, no markdown fence:
{"verdict": "supported"|"misattributed"|"unsupported", \
"correct_ref": "<the reference that SHOULD have been cited, or 'n/a'>", \
"reason": "<one sentence>"}"""

FAITHFULNESS_PROMPT = """You are auditing a legal question-answering system for \
Nigerian disability rights. It must answer STRICTLY from the retrieved \
excerpts, with no outside knowledge.

Judge ONE thing: is every factual claim in the ANSWER supported by the \
CONTEXT? Count a claim as unsupported if it states anything the context does \
not say, even if it is true in the real world.

CONTEXT:
%s

ANSWER:
%s

Reply with ONLY a JSON object, no markdown fence:
{"all_supported": true|false, "n_claims": <int>, "n_unsupported": <int>, \
"unsupported": ["<claim>", ...], "reason": "<one sentence>"}"""


def build_tasks(questions, recs, rows, ret) -> list[dict]:
    """Priority-ordered judging tasks. The 13 that decide A/B/C come first."""
    hits_by_q = {}
    for i, q in enumerate(questions):
        hits_by_q["Q%d" % (i + 1)] = ret.query(q, k=K_PER_DOC)[:TOP_N]

    def ctx(qid: str) -> str:
        return "\n\n".join(
            "%s:\n%s" % (cite_tag(h.doc_id, h.ref), " ".join(h.text.split()))
            for h in hits_by_q[qid])

    tasks: list[dict] = []

    # -- A. reverse_rel arbitration. The proxy scores relevancy by querying the
    #    corpus WITH the answer and checking where the top-3 hits land. That is
    #    a mirror of RAGAS's reverse-generation idea, but it measures retrieval,
    #    not aboutness. Asking the judge directly is the only way to tell an
    #    artifact from a real failure.
    for i, q in enumerate(questions):
        qid = "Q%d" % (i + 1)
        rec = recs[qid]
        if rec["refused"]:
            continue  # refusals are excluded from relevancy by the proxy too
        tasks.append({
            "id": "%s-relevancy" % qid, "qid": qid, "kind": "relevancy",
            "prompt": RELEVANCY_PROMPT % (q, rec["answer_full"]),
        })

    # -- B. thinness. Q3 and Q8 are the two the eval flagged as suspicious
    #    (Q3 coverage 0.600 / revrel 0.333; Q8 coverage 0.250).
    for qid in ("Q3", "Q8"):
        i = int(qid[1:]) - 1
        tasks.append({
            "id": "%s-thinness" % qid, "qid": qid, "kind": "thinness",
            "prompt": THINNESS_PROMPT % (
                questions[i], ctx(qid), recs[qid]["answer_full"]),
        })

    # -- C. citation dispositions. These are the two claims that used to need
    #    hand-written MANUAL_FLAGS entries. fix B now catches the s.39 one
    #    mechanically; the judge is the independent check on whether that
    #    mechanical verdict is actually RIGHT, not merely convenient.
    for qid, tag_sub, needle in (("Q10", "Constitution s. 39", "High Court"),
                                 ("Q9", "Constitution s. 34", "dignity")):
        row = next(r for r in rows if r["id"] == qid)
        claim = next((c for c in row["claims"] if tag_sub in c["tag"]), None)
        if claim is None:
            # The tag is simply not in the frozen answer any more. That is a
            # real, reportable outcome (fix A already removed the s.33 case),
            # not something to invent a judgement for.
            tasks.append({"id": "%s-cite" % qid, "qid": qid, "kind": "citation",
                          "skipped": "tag %r absent from frozen answer" % tag_sub})
            continue
        nums = {int(n) for n in re.findall(r"\d+", claim["tag"])}
        carrying = [h for h in hits_by_q[qid] if ref_nums(h.ref) & nums]
        text = ("\n\n".join(" ".join(h.text.split()) for h in carrying)
                if carrying else
                "(NOTHING in the retrieved context carries this reference.)")
        tasks.append({
            "id": "%s-cite" % qid, "qid": qid, "kind": "citation",
            "tag": claim["tag"], "needle": needle,
            "prompt": CITATION_PROMPT % (claim["claim_tail"], claim["tag"], text),
        })

    # -- D. supplementary faithfulness. Lowest priority: the proxy already
    #    measures this and fix B hardened it, so these only corroborate. They
    #    run last so a 429 cannot cost us the A/B/C verdict.
    for i, q in enumerate(questions):
        qid = "Q%d" % (i + 1)
        if recs[qid]["refused"]:
            continue
        tasks.append({
            "id": "%s-faithfulness" % qid, "qid": qid, "kind": "faithfulness",
            "prompt": FAITHFULNESS_PROMPT % (ctx(qid), recs[qid]["answer_full"]),
        })
    return tasks


def parse_json(text: str) -> dict:
    """Judges sometimes wrap JSON in a markdown fence despite instructions."""
    t = text.strip()
    if t.startswith("```"):
        t = re.sub(r"^```[a-zA-Z]*\s*", "", t)
        t = re.sub(r"\s*```$", "", t)
    try:
        return json.loads(t)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", t, re.S)
        if m:
            try:
                return json.loads(m.group(0))
            except json.JSONDecodeError:
                pass
    # Unparseable is NOT a verdict. Surfaced as an error, left pending.
    raise ValueError("judge did not return parseable JSON: %r" % text[:200])


# Free tier enforces 10 requests/MINUTE/model as well as a daily cap. The first
# run of this script treated every 429 as terminal and burned 9 tasks against a
# limit that clears in under a minute -- the error even carries
# `retryDelay: 37s` and `quotaId: ...PerMinutePerProjectPerModel...`. Pace
# below the limit, and honour the server's own retry hint.
MIN_INTERVAL = 7.0   # seconds between calls: 10/min with headroom
MAX_RETRIES = 4
_last_call = [0.0]


def _is_per_minute(err: str) -> bool:
    """Distinguish a transient RPM limit from the daily cap.

    This distinction is the whole reason a run can be honest about what it
    did: an RPM 429 deserves a retry, a daily-cap 429 must leave the row
    PENDING rather than pretend the answer was unobtainable for a trivial
    reason. Guessing wrong in the lenient direction would mean hammering a
    exhausted daily quota; guessing wrong in the strict direction would mean
    abandoning work that a 40-second wait would have completed.
    """
    return "PerMinute" in err or "RequestsPerMinute" in err


def _retry_delay(err: str, attempt: int) -> float:
    m = re.search(r"retryDelay['\"]?:\s*['\"]?(\d+(?:\.\d+)?)s", err)
    if m:
        return float(m.group(1)) + 3.0        # the server's own hint + slack
    return min(60.0, 8.0 * (2 ** attempt))    # else exponential backoff


def judge_call(prompt: str, model: str) -> tuple[str, int]:
    """One judged generation. Returns (text, attempts_consumed).

    Retries ONLY per-minute rate limits and 503 transients. A daily-quota 429
    propagates so the caller records it as pending -- never faked.
    """
    key = os.environ.get("GOOGLE_API_KEY") or os.environ.get("GEMINI_API_KEY")
    if not key:
        raise RuntimeError("GOOGLE_API_KEY/GEMINI_API_KEY not set")
    from google import genai
    client = genai.Client(api_key=key)

    attempts = 0
    for attempt in range(MAX_RETRIES):
        gap = time.time() - _last_call[0]
        if gap < MIN_INTERVAL:
            time.sleep(MIN_INTERVAL - gap)
        try:
            _last_call[0] = time.time()
            attempts += 1
            resp = client.models.generate_content(model=model, contents=prompt)
            return (resp.text or "").strip(), attempts
        except Exception as e:
            msg = "%s" % e
            transient = ("503" in msg or "UNAVAILABLE" in msg
                         or ("429" in msg and _is_per_minute(msg)))
            if not transient or attempt == MAX_RETRIES - 1:
                raise
            wait = _retry_delay(msg, attempt)
            print("       rate-limited, sleeping %.0fs (attempt %d/%d)"
                  % (wait, attempt + 1, MAX_RETRIES))
            time.sleep(wait)
    raise RuntimeError("unreachable")


def load_checkpoint() -> dict:
    if CHECKPOINT.exists():
        return json.loads(CHECKPOINT.read_text(encoding="utf-8"))
    return {}


def save_checkpoint(done: dict) -> None:
    CHECKPOINT.write_text(json.dumps(done, indent=1), encoding="utf-8")


def main() -> None:
    limit = None
    dry = "--dry-run" in sys.argv
    for a in sys.argv[1:]:
        if a.startswith("--limit="):
            limit = int(a[len("--limit="):])

    questions = load_questions()
    assert len(questions) == 10
    recs = {r["id"]: r for r in json.loads(
        TRANSCRIPT.read_text(encoding="utf-8")) if r["id"].startswith("Q")}
    eval_path = ROOT / "scripts" / "eval_m2.json"
    assert eval_path.exists(), (
        "run eval_phase06.py --out=scripts/eval_m2.json first (post-fix-B rows)")
    rows = json.loads(eval_path.read_text(encoding="utf-8"))

    ret = PerDocRetriever(build_corpus())
    tasks = build_tasks(questions, recs, rows, ret)
    done = load_checkpoint()

    pending = [t for t in tasks if t["id"] not in done and "skipped" not in t]
    print("judge model : %s   (generator was %s -- deliberately different)"
          % (JUDGE_MODEL, MODEL_NAME))
    print("tasks total : %d  | already checkpointed: %d  | to call: %d"
          % (len(tasks), len(done), len(pending)))
    for t in tasks:
        if "skipped" in t:
            print("  SKIP %-18s %s" % (t["id"], t["skipped"]))

    if dry:
        print("\n--dry-run: no calls made. Planned order:")
        for i, t in enumerate(pending, 1):
            print("  %2d. %-20s %s" % (i, t["id"], t["kind"]))
        return

    spent, failed = 0, 0
    for t in tasks:
        if "skipped" in t:
            done.setdefault(t["id"], {"id": t["id"], "qid": t["qid"],
                                      "kind": t["kind"], "skipped": t["skipped"]})
            continue
        if t["id"] in done and "llm_error" not in done[t["id"]]:
            continue
        if limit is not None and spent >= limit:
            print("  (--limit=%d reached; %d tasks still pending)"
                  % (limit, len(pending) - spent))
            break
        try:
            raw, used = judge_call(t["prompt"], JUDGE_MODEL)
            verdict = parse_json(raw)
            done[t["id"]] = {"id": t["id"], "qid": t["qid"], "kind": t["kind"],
                             "judge_model": JUDGE_MODEL,
                             "verdict": verdict, "raw": raw,
                             "attempts": used,
                             "at": datetime.now().isoformat(timespec="seconds")}
            spent += used
            print("  OK   %-20s %s" % (t["id"], json.dumps(verdict)[:110]))
        except Exception as e:  # quota / network / unparseable: stay PENDING
            failed += 1
            spent += 1  # a 429 still consumed an attempt; count it honestly
            done[t["id"]] = {"id": t["id"], "qid": t["qid"], "kind": t["kind"],
                             "judge_model": JUDGE_MODEL,
                             "llm_error": "%s: %s" % (type(e).__name__, e),
                             "at": datetime.now().isoformat(timespec="seconds")}
            print("  FAIL %-20s %s: %s" % (t["id"], type(e).__name__, str(e)[:90]))
        save_checkpoint(done)  # after EVERY call, so a 429 loses nothing

    ok = [v for v in done.values() if "verdict" in v]
    err = [v for v in done.values() if "llm_error" in v]
    print("\n== QUOTA LEDGER (%s) ==" % date.today().isoformat())
    print("  judge model      : %s" % JUDGE_MODEL)
    print("  attempts this run: %d" % spent)
    print("  verdicts recorded: %d" % len(ok))
    print("  still pending    : %d %s" % (len(err), [e["id"] for e in err]))
    print("  generator model  : %s -- 0 calls (separate free-tier pool)"
          % MODEL_NAME)

    OUT.write_text(json.dumps(sorted(done.values(), key=lambda r: r["id"]),
                              indent=1), encoding="utf-8")
    print("wrote %s (%d records)" % (OUT, len(done)))
    summarise(done, rows)


def ceiling(row_of: dict) -> None:
    """Deterministic, zero-LLM ceiling analysis for reverse_rel.

    This exists so verdict A does not rest on the judge alone. A judge that
    answers "relevant" to all nine questions is, on its own, weak evidence --
    assent bias is the classic LLM-judge failure mode. This computes the same
    conclusion from arithmetic instead.

    reverse_rel queries the corpus WITH the answer text and scores the fraction
    of the merged top-3 whose ref lands in the expected set. But the retriever
    is a PerDocRetriever: it returns top-k from EVERY doc by design, so the
    top-3 routinely contains hits from documents that EXPECTED does not name
    at all. Those are misses by construction, no matter how good the answer is.
    That is the same locked per-doc-merging trade-off that makes context
    precision 0.333 "by design" -- reverse_rel simply inherits it, undeclared.

    So the interesting number is not the score but the score's CEILING: the
    fraction of the reverse top-3 that could possibly count.
    """
    questions = load_questions()
    recs = {r["id"]: r for r in json.loads(
        TRANSCRIPT.read_text(encoding="utf-8")) if r["id"].startswith("Q")}
    ret = PerDocRetriever(build_corpus())
    print("\n== A-PRIME. reverse_rel STRUCTURAL CEILING (no LLM, deterministic) ==")
    print("  %-5s %-14s %-20s %-10s %-8s %s"
          % ("qid", "EXPECTED docs", "reverse top-3 docs", "countable", "actual", "ceiling"))
    caps, acts = [], []
    for i in range(len(questions)):
        qid = "Q%d" % (i + 1)
        if recs[qid]["refused"]:
            continue
        exp = EXPECTED[qid]
        rev = ret.query(recs[qid]["answer_full"], k=3)[:3]
        if not rev:
            continue
        countable = sum(1 for h in rev if h.doc_id in exp)
        actual = row_of[qid].get("reverse_rel")
        cap = countable / len(rev)
        caps.append(cap)
        acts.append(actual if actual is not None else 0.0)
        print("  %-5s %-14s %-20s %-10s %-8.3f %.3f%s"
              % (qid, ",".join(sorted(d[:4] for d in exp)),
                 ",".join(h.doc_id[:4] for h in rev),
                 "%d/%d" % (countable, len(rev)),
                 actual if actual is not None else 0.0, cap,
                 "  <-- HARD-CAPPED" if cap < 0.8 else ""))
    mc = sum(caps) / len(caps)
    ma = sum(acts) / len(acts)
    print("  mean ceiling %.3f vs gate 0.80 -- a PERFECT system could score at "
          "most %.3f here." % (mc, mc))
    print("  mean actual  %.3f = %.0f%% of what is even achievable."
          % (ma, 100 * ma / mc))
    print("  Q3/Q8 are hard-capped at 0.333: their reverse top-3 is dominated by "
          "docs EXPECTED\n  does not name, so most of their score is unreachable "
          "by construction, not by fault.")


def summarise(done: dict, rows: list) -> None:
    """Proxy vs judge, side by side. The comparison happens HERE, in code,
    never in the prompt -- the judge never saw a proxy score."""
    by = lambda kind: [v for v in done.values()
                       if v.get("kind") == kind and "verdict" in v]
    row_of = {r["id"]: r for r in rows}

    rel = by("relevancy")
    if rel:
        ceiling(row_of)
        print("\n== A. reverse_rel 0.630: ARTIFACT OR REAL? ==")
        print("  %-5s %-10s %-9s %s" % ("qid", "proxy", "judge", "judge reason"))
        agree = 0
        for v in sorted(rel, key=lambda r: int(r["qid"][1:])):
            p = row_of[v["qid"]].get("reverse_rel")
            j = v["verdict"]
            jr = bool(j.get("relevant"))
            if (p is not None and p >= 0.8) == jr:
                agree += 1
            print("  %-5s %-10s %-9s %s" % (
                v["qid"], "n/a" if p is None else "%.3f" % p,
                "RELEVANT" if jr else "NOT",
                str(j.get("reason", ""))[:72]))
        n_rel = sum(1 for v in rel if v["verdict"].get("relevant"))
        print("  judge: %d/%d answers relevant; proxy-vs-judge agreement %d/%d"
              % (n_rel, len(rel), agree, len(rel)))

    thin = by("thinness")
    if thin:
        print("\n== B. Q3/Q8 ANSWER THINNESS ==")
        for v in thin:
            j = v["verdict"]
            print("  %-5s %-18s missed: %s" % (
                v["qid"], j.get("verdict"), str(j.get("missed"))[:80]))

    cite = by("citation")
    if cite:
        print("\n== C. CITATION DISPOSITIONS (s.39 / s.34) ==")
        for v in cite:
            j = v["verdict"]
            print("  %-5s %-15s should be: %-16s %s" % (
                v["qid"], j.get("verdict"), j.get("correct_ref"),
                str(j.get("reason", ""))[:60]))
    for v in done.values():
        if v.get("kind") == "citation" and "skipped" in v:
            print("  %-5s SKIPPED: %s" % (v["qid"], v["skipped"]))

    faith = by("faithfulness")
    if faith:
        print("\n== D. FAITHFULNESS (corroboration; proxy already gates this) ==")
        print("  %-5s %-8s %-8s %s" % ("qid", "proxy", "judge", "unsupported"))
        for v in sorted(faith, key=lambda r: int(r["qid"][1:])):
            j = v["verdict"]
            print("  %-5s %-8.3f %-8s %s" % (
                v["qid"], row_of[v["qid"]]["faithfulness_audited"],
                "OK" if j.get("all_supported") else "%d BAD" % j.get("n_unsupported", 0),
                str(j.get("unsupported", ""))[:60]))


if __name__ == "__main__":
    main()
